# Generated by Django 5.1.2 on 2024-10-15 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sportsapp', '0003_alter_area_created_at_alter_match_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='area',
            name='city',
            field=models.CharField(help_text='City where the area is located', max_length=100),
        ),
        migrations.AlterField(
            model_name='area',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the area was created'),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(help_text='Name of the area', max_length=100),
        ),
        migrations.AlterField(
            model_name='match',
            name='away_team',
            field=models.ForeignKey(help_text='Away team of the match', on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='sportsapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the match was created'),
        ),
        migrations.AlterField(
            model_name='match',
            name='date',
            field=models.DateTimeField(help_text='Date and time of the match'),
        ),
        migrations.AlterField(
            model_name='match',
            name='home_team',
            field=models.ForeignKey(help_text='Home team of the match', on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='sportsapp.team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='location',
            field=models.ForeignKey(help_text='Location where the match is held', on_delete=django.db.models.deletion.CASCADE, to='sportsapp.area'),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='age',
            field=models.IntegerField(help_text='Age of the player'),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the player was added'),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='name',
            field=models.CharField(help_text='Name of the player', max_length=100),
        ),
        migrations.AlterField(
            model_name='playerdetail',
            name='team',
            field=models.ForeignKey(help_text='Team to which the player belongs', on_delete=django.db.models.deletion.CASCADE, to='sportsapp.team'),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach',
            field=models.CharField(help_text='Name of the coach', max_length=100),
        ),
        migrations.AlterField(
            model_name='team',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Time when the team was created'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(help_text='Name of the team', max_length=100),
        ),
    ]
